services:
  bot:
    build:
      context: ./bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      API_BASE_URL: http://llm:8000
      APP_ENV: prod
    volumes:
      - "./db:/app/db"
    restart: unless-stopped

  llm:
    build:
      context: ./llm
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PROXY_URL: ${PROXY_URL}
    expose:
      - 8000
    restart: unless-stopped

#  parser:
#    image: arsanoshin/news-parser:latest
#    environment:
#      API_ID: ${API_ID}
#      API_HASH: ${API_HASH}
#      CHANNEL: bbbreaking
#      BOT_USERNAME: @newsdudebot
#    restart: unless-stopped